// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CheckFileOwner(ctx context.Context, arg CheckFileOwnerParams) (bool, error)
	CheckReferralCodeExists(ctx context.Context, referralCode pgtype.Text) (bool, error)
	CheckUserHasAnyRole(ctx context.Context, userID int64) (bool, error)
	ConfirmUpload(ctx context.Context, arg ConfirmUploadParams) (File, error)
	CountAllUserPhoneNumbers(ctx context.Context, userID int64) (int64, error)
	CreateCandidatePlaceholder(ctx context.Context, arg CreateCandidatePlaceholderParams) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMoreInfoAboutThisUser(ctx context.Context, arg CreateMoreInfoAboutThisUserParams) (int64, error)
	CreatePhoneNumber(ctx context.Context, arg CreatePhoneNumberParams) (int64, error)
	CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateUserNIN(ctx context.Context, arg CreateUserNINParams) (int64, error)
	CreateUserReferralRecord(ctx context.Context, arg CreateUserReferralRecordParams) error
	CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (int64, error)
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserPhoneNumber(ctx context.Context, arg DeleteUserPhoneNumberParams) error
	DeleteUserRoles(ctx context.Context, userID int64) error
	// Returns all distinct election_group_ids for a user's applications under a party.
	GetApplicationElectionGroupsByUserAndParty(ctx context.Context, arg GetApplicationElectionGroupsByUserAndPartyParams) ([]int64, error)
	GetFileByID(ctx context.Context, id int64) (File, error)
	GetFileByKey(ctx context.Context, fileKey string) (File, error)
	GetFileByPublicUrl(ctx context.Context, publicUrl string) (File, error)
	GetMoreInfoAboutThisUser(ctx context.Context, userID int64) (UserMoreInfo, error)
	GetPublicIDByAdditionalPhone(ctx context.Context, phone string) (string, error)
	GetPublicIDByEmail(ctx context.Context, email pgtype.Text) (string, error)
	GetPublicIDByPhone(ctx context.Context, phone pgtype.Text) (string, error)
	GetPublicIDByUserID(ctx context.Context, id int64) (string, error)
	GetPublicIDByUsername(ctx context.Context, username pgtype.Text) (string, error)
	GetReferral(ctx context.Context, id int64) (Referral, error)
	GetReferralByReferredUserID(ctx context.Context, referredUserID int64) (Referral, error)
	GetReferrerNameByCode(ctx context.Context, referralCode pgtype.Text) (GetReferrerNameByCodeRow, error)
	// Returns all user_referrals records for a referrer under a specific party.
	GetReferrerUserReferralsForParty(ctx context.Context, arg GetReferrerUserReferralsForPartyParams) ([]UserReferral, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetSystemSetting(ctx context.Context, key string) (SystemSetting, error)
	UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) (SystemSetting, error)
	GetUserByFakeID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error)
	GetUserIDByNIN(ctx context.Context, nin string) (int64, error)
	GetUserIdByReferralCode(ctx context.Context, referralCode pgtype.Text) (int64, error)
	GetUserNINByUserID(ctx context.Context, userID int64) (UsersNin, error)
	GetUserPasswordHashByFakeID(ctx context.Context, publicID string) (string, error)
	GetUserPasswordHashByPublicID(ctx context.Context, publicID string) (string, error)
	GetUserPhoneNumbersByUserID(ctx context.Context, userID int64) ([]UsersPhoneNumber, error)
	GetUserPreferencesByUserID(ctx context.Context, userID int64) (UserPreference, error)
	GetUserReferralByID(ctx context.Context, id int64) (UserReferral, error)
	GetUserReferralByUserAndElectionGroup(ctx context.Context, arg GetUserReferralByUserAndElectionGroupParams) (UserReferral, error)
	// Returns the referrer_user_id for a user given their internal user ID.
	GetUserReferredByID(ctx context.Context, referredUserID int64) (int64, error)
	GetUserRoles(ctx context.Context, userID int64) ([]GetUserRolesRow, error)
	GetUserVerification(ctx context.Context, userID int64) (UserVerification, error)
	HardDeleteFile(ctx context.Context, id int64) error
	// Increments agent_referrals for the referrer's user_referrals row matching the election group.
	IncrementUserReferralAgentCount(ctx context.Context, arg IncrementUserReferralAgentCountParams) error
	IncrementUserReferralAgentCountByID(ctx context.Context, id int64) error
	IncrementUserReferralEarnedAmountByID(ctx context.Context, arg IncrementUserReferralEarnedAmountByIDParams) error
	IncrementUserReferralPotentialEarningsByID(ctx context.Context, arg IncrementUserReferralPotentialEarningsByIDParams) error
	// Increments total_referrals count for the selected user_referrals record.
	IncrementUserReferralTotalCount(ctx context.Context, id int64) error
	// Increments unpaid_referrals for the referrer's user_referrals row matching the election group.
	IncrementUserReferralUnpaidCount(ctx context.Context, arg IncrementUserReferralUnpaidCountParams) error
	IncrementUserReferralUnpaidCountByID(ctx context.Context, id int64) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertUserPreferences(ctx context.Context, arg InsertUserPreferencesParams) (UserPreference, error)
	ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error)
	ListReferrals(ctx context.Context, arg ListReferralsParams) ([]Referral, error)
	ListReferralsByReferrer(ctx context.Context, arg ListReferralsByReferrerParams) ([]Referral, error)
	ListReferredUsersWithDetails(ctx context.Context, arg ListReferredUsersWithDetailsParams) ([]ListReferredUsersWithDetailsRow, error)
	// ListUsers fetches a paginated list of users with optional filtering.
	// We use sqlc.narg() (nullable argument) to make filters optional:
	// If a parameter like 'cursor' is not provided (null), the 'sqlc.narg('cursor')::bigint IS NULL'
	// condition becomes true, effectively skipping that filter.
	// This allows us to use a single dynamic query instead of writing multiple separate queries.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	MarkFileDeleted(ctx context.Context, id int64) (File, error)
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	SeedUser(ctx context.Context, arg SeedUserParams) (int64, error)
	UpdateFileOwner(ctx context.Context, arg UpdateFileOwnerParams) (File, error)
	UpdateMoreInfoAboutThisUser(ctx context.Context, arg UpdateMoreInfoAboutThisUserParams) error
	UpdateOnboardingProfile(ctx context.Context, arg UpdateOnboardingProfileParams) (User, error)
	UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error
	UpdateReferral(ctx context.Context, arg UpdateReferralParams) (Referral, error)
	// Updates the referrals row when the referred user is accepted as an agent.
	// Sets milestone, amount_to_pay, party_id, election_group_id.
	UpdateReferralOnAgentAcceptance(ctx context.Context, arg UpdateReferralOnAgentAcceptanceParams) error
	// Updates the referrals row when the referred user submits a party application matching referrer's user_referrals.
	UpdateReferralOnApplication(ctx context.Context, arg UpdateReferralOnApplicationParams) error
	UpdateUserAgentMoreInfo(ctx context.Context, arg UpdateUserAgentMoreInfoParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserDegreeCertificateUrl(ctx context.Context, arg UpdateUserDegreeCertificateUrlParams) error
	UpdateUserFakeID(ctx context.Context, arg UpdateUserPublicIDParams) error
	UpdateUserHasRole(ctx context.Context, arg UpdateUserHasRoleParams) error
	UpdateUserPasswordByFid(ctx context.Context, arg UpdateUserPasswordByPublicIDParams) error
	UpdateUserPasswordByPublicID(ctx context.Context, arg UpdateUserPasswordByPublicIDParams) error
	UpdateUserPreferencesByUserID(ctx context.Context, arg UpdateUserPreferencesByUserIDParams) (UserPreference, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserPublicID(ctx context.Context, arg UpdateUserPublicIDParams) error
	UpdateUserReferralCode(ctx context.Context, arg UpdateUserReferralCodeParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserVotersCard(ctx context.Context, arg UpdateUserVotersCardParams) error
	UpsertUserPhoneNumber(ctx context.Context, arg UpsertUserPhoneNumberParams) (int64, error)
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
