// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"
	"fmt"
	"time"

	"chipa/api/internal/crypto"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateUser = `-- name: AdminUpdateUser :exec
UPDATE users
SET username = COALESCE(NULLIF($2, ''), username),
    current_country = COALESCE(NULLIF($3, 0), current_country),
    current_state = COALESCE(NULLIF($4, 0), current_state),
    updated_at = NOW()
WHERE id = $1
`

type AdminUpdateUserParams struct {
	ID             int64       `json:"id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Username       pgtype.Text `json:"username"`
	Gender         pgtype.Text `json:"gender"`
	Avatar         pgtype.Text `json:"avatar"`
	AvatarFileID   pgtype.Int8 `json:"avatar_file_id"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
	StateOfOrigin  pgtype.Int2 `json:"state_of_origin"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) error {
	_, err := q.db.Exec(ctx, adminUpdateUser,
		arg.ID,
		arg.Username.String,
		arg.CurrentCountry,
		arg.CurrentState,
	)
	if err != nil {
		return err
	}

	_, err = q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, first_name, last_name, middle_name, gender, profile_photo_url, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, NOW())
		ON CONFLICT (user_id) DO UPDATE
		SET first_name = COALESCE(NULLIF(EXCLUDED.first_name, ''), user_profiles.first_name),
		    last_name = COALESCE(NULLIF(EXCLUDED.last_name, ''), user_profiles.last_name),
		    middle_name = COALESCE(NULLIF(EXCLUDED.middle_name, ''), user_profiles.middle_name),
		    gender = COALESCE(NULLIF(EXCLUDED.gender, ''), user_profiles.gender),
		    profile_photo_url = COALESCE(NULLIF(EXCLUDED.profile_photo_url, ''), user_profiles.profile_photo_url),
		    updated_at = NOW()
	`, arg.ID, arg.FirstName.String, arg.LastName.String, arg.MiddleName.String, arg.Gender.String, arg.Avatar.String)
	return err
}

const checkReferralCodeExists = `-- name: CheckReferralCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE referral_code = $1
)
`

func (q *Queries) CheckReferralCodeExists(ctx context.Context, referralCode pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkReferralCodeExists, referralCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAllUserPhoneNumbers = `-- name: CountAllUserPhoneNumbers :one
SELECT COUNT(*) FROM users_phone_numbers
WHERE user_id = $1
`

func (q *Queries) CountAllUserPhoneNumbers(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUserPhoneNumbers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidatePlaceholder = `-- name: CreateCandidatePlaceholder :one
INSERT INTO users (
  email, password_hash, username, last_name, first_name, middle_name,
  gender, date_of_birth, current_country, current_state, current_city, state_of_origin,
  party_id, avatar, avatar_file_id, account_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, 'placeholder')
RETURNING id
`

type CreateCandidatePlaceholderParams struct {
	Email          pgtype.Text `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	Username       pgtype.Text `json:"username"`
	LastName       pgtype.Text `json:"last_name"`
	FirstName      pgtype.Text `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Gender         pgtype.Text `json:"gender"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
	StateOfOrigin  pgtype.Int2 `json:"state_of_origin"`
	PartyID        pgtype.Int2 `json:"party_id"`
	Avatar         pgtype.Text `json:"avatar"`
	AvatarFileID   pgtype.Int8 `json:"avatar_file_id"`
}

func (q *Queries) CreateCandidatePlaceholder(ctx context.Context, arg CreateCandidatePlaceholderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCandidatePlaceholder,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentCity,
		arg.StateOfOrigin,
		arg.PartyID,
		arg.Avatar,
		arg.AvatarFileID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type CreateMoreInfoAboutThisUserParams struct {
	UserID            int64       `json:"user_id"`
	OccupationID      pgtype.Int2 `json:"occupation_id"`
	EducationalStatus pgtype.Text `json:"educational_status"`
	HighestDegree     pgtype.Text `json:"highest_degree"`
	GraduationYear    pgtype.Text `json:"graduation_year"`
	SchoolName        pgtype.Text `json:"school_name"`
	Religion          pgtype.Text `json:"religion"`
	MaritalStatus     pgtype.Text `json:"marital_status"`
	Address           pgtype.Text `json:"address"`
}

func (q *Queries) CreateMoreInfoAboutThisUser(ctx context.Context, arg CreateMoreInfoAboutThisUserParams) (int64, error) {
	_, _ = q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, employment_status, updated_at)
		VALUES ($1, $2, NOW())
		ON CONFLICT (user_id) DO UPDATE
		SET employment_status = COALESCE(NULLIF(EXCLUDED.employment_status, ''), user_profiles.employment_status),
		    updated_at = NOW()
	`, arg.UserID, arg.EducationalStatus.String)

	if arg.Address.Valid && arg.Address.String != "" {
		_, _ = q.db.Exec(ctx, `
			INSERT INTO addresses (user_id, address_type, line_1, city, country_code, is_current, updated_at)
			VALUES ($1, 'residential', $2, 'Unknown', 'NG', true, NOW())
			ON CONFLICT DO NOTHING
		`, arg.UserID, arg.Address.String)
	}
	return arg.UserID, nil
}

const createPhoneNumber = `-- name: CreatePhoneNumber :one
INSERT INTO users_phone_numbers (user_id, phone, phonecode, raw_input, on_whatsapp, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreatePhoneNumberParams struct {
	UserID     int64       `json:"user_id"`
	Phone      string      `json:"phone"`
	Phonecode  string      `json:"phonecode"`
	RawInput   string      `json:"raw_input"`
	OnWhatsapp pgtype.Bool `json:"on_whatsapp"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) CreatePhoneNumber(ctx context.Context, arg CreatePhoneNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPhoneNumber,
		arg.UserID,
		arg.Phone,
		arg.Phonecode,
		arg.RawInput,
		arg.OnWhatsapp,
		arg.IsDefault,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type CreateUserParams struct {
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Username       pgtype.Text `json:"username"`
	PasswordHash   string      `json:"password_hash"`
	LastName       pgtype.Text `json:"last_name"`
	FirstName      pgtype.Text `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Gender         pgtype.Text `json:"gender"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	pubID := crypto.GeneratePublicID("usr")
	row := q.db.QueryRow(ctx, `
		INSERT INTO users (public_id, email, phone, username, password_hash, current_country, current_state)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id
	`,
		pubID,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.PasswordHash,
		arg.CurrentCountry,
		arg.CurrentState,
	)
	var id int64
	err := row.Scan(&id)
	if err != nil {
		return 0, err
	}

	if arg.FirstName.Valid || arg.LastName.Valid {
		var dobVal *time.Time
		if arg.DateOfBirth.Valid {
			dobVal = &arg.DateOfBirth.Time
		}
		_, _ = q.db.Exec(ctx, `
			INSERT INTO user_profiles (user_id, first_name, last_name, middle_name, gender, date_of_birth, updated_at)
			VALUES ($1, $2, $3, $4, $5, $6, NOW())
			ON CONFLICT (user_id) DO NOTHING
		`, id, arg.FirstName.String, arg.LastName.String, arg.MiddleName.String, arg.Gender.String, dobVal)
	}

	_, _ = q.db.Exec(ctx, `
		INSERT INTO user_verifications (user_id)
		VALUES ($1)
		ON CONFLICT (user_id) DO NOTHING
	`, id)

	return id, nil
}

type CreateUserNINParams struct {
	UserID int64  `json:"user_id"`
	Nin    string `json:"nin"`
}

func (q *Queries) CreateUserNIN(ctx context.Context, arg CreateUserNINParams) (int64, error) {
	vault := crypto.NewVault()
	enc, err := vault.Encrypt(arg.Nin)
	if err != nil {
		return 0, err
	}
	hash := vault.BlindIndex(arg.Nin)
	row := q.db.QueryRow(ctx, `
		INSERT INTO identity_documents (user_id, document_type, document_number_encrypted, document_number_hash, status, verified_at)
		VALUES ($1, 'nin', $2, $3, 'verified', NOW())
		ON CONFLICT (user_id, document_type) DO UPDATE
		SET document_number_encrypted = EXCLUDED.document_number_encrypted,
		    document_number_hash = EXCLUDED.document_number_hash,
		    status = 'verified',
		    verified_at = NOW(),
		    updated_at = NOW()
		RETURNING id
	`, arg.UserID, enc, hash)
	var id int64
	err = row.Scan(&id)
	return id, err
}

type CreateUserVerificationParams struct {
	UserID             int64       `json:"user_id"`
	NinVerified        pgtype.Bool `json:"nin_verified"`
	PhoneVerified      pgtype.Bool `json:"phone_verified"`
	EmailVerified      pgtype.Bool `json:"email_verified"`
	VotersCardVerified pgtype.Bool `json:"voters_card_verified"`
}

func (q *Queries) CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, `
		INSERT INTO user_verifications (user_id, nin_verified, phone_verified, email_verified)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT (user_id) DO UPDATE
		SET nin_verified = EXCLUDED.nin_verified,
		    phone_verified = EXCLUDED.phone_verified,
		    email_verified = EXCLUDED.email_verified,
		    updated_at = NOW()
		RETURNING user_id
	`, arg.UserID, arg.NinVerified.Bool, arg.PhoneVerified.Bool, arg.EmailVerified.Bool)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET account_status = 'deleted'
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserPhoneNumber = `-- name: DeleteUserPhoneNumber :exec
DELETE FROM users_phone_numbers
WHERE id = $1 AND user_id = $2
`

type DeleteUserPhoneNumberParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserPhoneNumber(ctx context.Context, arg DeleteUserPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, deleteUserPhoneNumber, arg.ID, arg.UserID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getPublicIDByAdditionalPhone = `-- name: GetPublicIDByAdditionalPhone :one
SELECT u.public_id
FROM users u
JOIN users_phone_numbers upn ON u.id = upn.user_id
WHERE upn.phone = $1 LIMIT 1
`

func (q *Queries) GetPublicIDByAdditionalPhone(ctx context.Context, phone string) (string, error) {
	row := q.db.QueryRow(ctx, getPublicIDByAdditionalPhone, phone)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

const getPublicIDByEmail = `-- name: GetPublicIDByEmail :one
SELECT public_id FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetPublicIDByEmail(ctx context.Context, email pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getPublicIDByEmail, email)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

const getPublicIDByPhone = `-- name: GetPublicIDByPhone :one
SELECT public_id FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetPublicIDByPhone(ctx context.Context, phone pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getPublicIDByPhone, phone)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

const getPublicIDByUserID = `-- name: GetPublicIDByUserID :one
SELECT public_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPublicIDByUserID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getPublicIDByUserID, id)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

const getPublicIDByUsername = `-- name: GetPublicIDByUsername :one
SELECT public_id FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetPublicIDByUsername(ctx context.Context, username pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getPublicIDByUsername, username)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

func (q *Queries) GetMoreInfoAboutThisUser(ctx context.Context, userID int64) (UserMoreInfo, error) {
	row := q.db.QueryRow(ctx, `
		SELECT up.user_id, COALESCE(a.line_1, '') 
		FROM user_profiles up 
		LEFT JOIN addresses a ON a.user_id = up.user_id AND a.is_current = true
		WHERE up.user_id = $1 LIMIT 1
	`, userID)
	var i UserMoreInfo
	var addr string
	err := row.Scan(&i.UserID, &addr)
	if err != nil {
		return UserMoreInfo{UserID: userID}, nil
	}
	i.Address = pgtype.Text{String: addr, Valid: addr != ""}
	return i, nil
}

const getReferrerNameByCode = `-- name: GetReferrerNameByCode :one
SELECT u.id, up.first_name, up.last_name 
FROM users u
LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE u.referral_code = $1 LIMIT 1
`

type GetReferrerNameByCodeRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

func (q *Queries) GetReferrerNameByCode(ctx context.Context, referralCode pgtype.Text) (GetReferrerNameByCodeRow, error) {
	row := q.db.QueryRow(ctx, getReferrerNameByCode, referralCode)
	var i GetReferrerNameByCodeRow
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT 
    u.id, 
    u.public_id, 
    u.email, 
    up.profile_photo_url::varchar AS avatar, 
    NULL::bigint AS avatar_file_id, 
    u.phone, 
    u.username, 
    u.password_hash, 
    COALESCE(up.last_name, '')::varchar AS last_name, 
    COALESCE(up.first_name, '')::varchar AS first_name, 
    up.middle_name::varchar AS middle_name, 
    up.gender::varchar AS gender, 
    up.date_of_birth, 
    NULL::varchar AS voters_card_image, 
    COALESCE(u.current_country, 161)::smallint AS current_country, 
    COALESCE(u.current_state, 0)::smallint AS current_state, 
    NULL::int AS current_city, 
    NULL::int AS current_lga, 
    NULL::int AS current_ward, 
    NULL::smallint AS country_of_origin, 
    NULL::smallint AS state_of_origin, 
    false AS is_politician, 
    COALESCE(uv.email_verified, false) AS is_verified, 
    false AS has_role, 
    NULL::smallint AS party_id, 
    NULL::int AS polling_unit_id, 
    u.account_status, 
    u.created_at, 
    u.updated_at,
    u.referral_code
FROM users u
LEFT JOIN user_profiles up ON up.user_id = u.id
LEFT JOIN user_verifications uv ON uv.user_id = u.id
WHERE u.public_id = $1 LIMIT 1
`

type GetUserByPublicIDRow struct {
	ID              int64              `json:"id"`
	PublicID        string             `json:"public_id"`
	Email           pgtype.Text        `json:"email"`
	Avatar          pgtype.Text        `json:"avatar"`
	AvatarFileID    pgtype.Int8        `json:"avatar_file_id"`
	Phone           pgtype.Text        `json:"phone"`
	Username        pgtype.Text        `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	LastName        pgtype.Text        `json:"last_name"`
	FirstName       pgtype.Text        `json:"first_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	Gender          pgtype.Text        `json:"gender"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	VotersCardImage pgtype.Text        `json:"voters_card_image"`
	CurrentCountry  int16              `json:"current_country"`
	CurrentState    int16              `json:"current_state"`
	CurrentCity     pgtype.Int4        `json:"current_city"`
	CurrentLga      pgtype.Int4        `json:"current_lga"`
	CurrentWard     pgtype.Int4        `json:"current_ward"`
	CountryOfOrigin pgtype.Int2        `json:"country_of_origin"`
	StateOfOrigin   pgtype.Int2        `json:"state_of_origin"`
	IsPolitician    pgtype.Bool        `json:"is_politician"`
	IsVerified      pgtype.Bool        `json:"is_verified"`
	HasRole         pgtype.Bool        `json:"has_role"`
	PartyID         pgtype.Int2        `json:"party_id"`
	PollingUnitID   pgtype.Int4        `json:"polling_unit_id"`
	AccountStatus   pgtype.Text        `json:"account_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReferralCode    pgtype.Text        `json:"referral_code"`
}

type GetUserByFakeIDRow = GetUserByPublicIDRow

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i GetUserByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.VotersCardImage,
		&i.CurrentCountry,
		&i.CurrentState,
		&i.CurrentCity,
		&i.CurrentLga,
		&i.CurrentWard,
		&i.CountryOfOrigin,
		&i.StateOfOrigin,
		&i.IsPolitician,
		&i.IsVerified,
		&i.HasRole,
		&i.PartyID,
		&i.PollingUnitID,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralCode,
	)
	return i, err
}

func (q *Queries) GetUserByFakeID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error) {
	return q.GetUserByPublicID(ctx, publicID)
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.id, 
    u.public_id, 
    u.email, 
    up.profile_photo_url::varchar AS avatar, 
    NULL::bigint AS avatar_file_id, 
    u.phone, 
    u.username, 
    u.password_hash, 
    COALESCE(up.last_name, '')::varchar AS last_name, 
    COALESCE(up.first_name, '')::varchar AS first_name, 
    up.middle_name::varchar AS middle_name, 
    up.gender::varchar AS gender, 
    up.date_of_birth, 
    NULL::varchar AS voters_card_image, 
    COALESCE(u.current_country, 161)::smallint AS current_country, 
    COALESCE(u.current_state, 0)::smallint AS current_state, 
    NULL::int AS current_city, 
    NULL::int AS current_lga, 
    NULL::int AS current_ward, 
    NULL::smallint AS country_of_origin, 
    NULL::smallint AS state_of_origin, 
    false AS is_politician, 
    COALESCE(uv.email_verified, false) AS is_verified, 
    false AS has_role, 
    NULL::smallint AS party_id, 
    NULL::int AS polling_unit_id, 
    u.account_status, 
    u.created_at, 
    u.updated_at,
    u.referral_code
FROM users u
LEFT JOIN user_profiles up ON up.user_id = u.id
LEFT JOIN user_verifications uv ON uv.user_id = u.id
WHERE u.id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID              int64              `json:"id"`
	PublicID        string             `json:"public_id"`
	Email           pgtype.Text        `json:"email"`
	Avatar          pgtype.Text        `json:"avatar"`
	AvatarFileID    pgtype.Int8        `json:"avatar_file_id"`
	Phone           pgtype.Text        `json:"phone"`
	Username        pgtype.Text        `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	LastName        pgtype.Text        `json:"last_name"`
	FirstName       pgtype.Text        `json:"first_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	Gender          pgtype.Text        `json:"gender"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	VotersCardImage pgtype.Text        `json:"voters_card_image"`
	CurrentCountry  int16              `json:"current_country"`
	CurrentState    int16              `json:"current_state"`
	CurrentCity     pgtype.Int4        `json:"current_city"`
	CurrentLga      pgtype.Int4        `json:"current_lga"`
	CurrentWard     pgtype.Int4        `json:"current_ward"`
	CountryOfOrigin pgtype.Int2        `json:"country_of_origin"`
	StateOfOrigin   pgtype.Int2        `json:"state_of_origin"`
	IsPolitician    pgtype.Bool        `json:"is_politician"`
	IsVerified      pgtype.Bool        `json:"is_verified"`
	HasRole         pgtype.Bool        `json:"has_role"`
	PartyID         pgtype.Int2        `json:"party_id"`
	PollingUnitID   pgtype.Int4        `json:"polling_unit_id"`
	AccountStatus   pgtype.Text        `json:"account_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReferralCode    pgtype.Text        `json:"referral_code"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.VotersCardImage,
		&i.CurrentCountry,
		&i.CurrentState,
		&i.CurrentCity,
		&i.CurrentLga,
		&i.CurrentWard,
		&i.CountryOfOrigin,
		&i.StateOfOrigin,
		&i.IsPolitician,
		&i.IsVerified,
		&i.HasRole,
		&i.PartyID,
		&i.PollingUnitID,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralCode,
	)
	return i, err
}

const getUserIDByNIN = `-- name: GetUserIDByNIN :one
SELECT user_id
FROM identity_documents
WHERE document_type = 'nin' AND document_number_hash = $1 LIMIT 1
`

func (q *Queries) GetUserIDByNIN(ctx context.Context, nin string) (int64, error) {
	hash := crypto.NewVault().BlindIndex(nin)
	row := q.db.QueryRow(ctx, getUserIDByNIN, hash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserIdByReferralCode = `-- name: GetUserIdByReferralCode :one
SELECT id FROM users
WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetUserIdByReferralCode(ctx context.Context, referralCode pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIdByReferralCode, referralCode)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserNINByUserID = `-- name: GetUserNINByUserID :one
SELECT id, user_id, document_number_encrypted FROM identity_documents
WHERE user_id = $1 AND document_type = 'nin' LIMIT 1
`

func (q *Queries) GetUserNINByUserID(ctx context.Context, userID int64) (UsersNin, error) {
	row := q.db.QueryRow(ctx, getUserNINByUserID, userID)
	var id, uID int64
	var enc []byte
	err := row.Scan(&id, &uID, &enc)
	if err != nil {
		return UsersNin{}, err
	}
	dec, err := crypto.NewVault().Decrypt(enc)
	if err != nil {
		return UsersNin{}, err
	}
	return UsersNin{
		ID:     id,
		UserID: uID,
		Nin:    dec,
	}, nil
}

const getUserPasswordHashByPublicID = `-- name: GetUserPasswordHashByPublicID :one
SELECT password_hash FROM users
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) GetUserPasswordHashByPublicID(ctx context.Context, publicID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHashByPublicID, publicID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

func (q *Queries) GetUserPasswordHashByFakeID(ctx context.Context, publicID string) (string, error) {
	return q.GetUserPasswordHashByPublicID(ctx, publicID)
}

const getUserPhoneNumbersByUserID = `-- name: GetUserPhoneNumbersByUserID :many
SELECT id, user_id, owner_is_verified, phone, raw_input, phonecode, on_whatsapp, is_default, is_active FROM users_phone_numbers
WHERE user_id = $1
`

func (q *Queries) GetUserPhoneNumbersByUserID(ctx context.Context, userID int64) ([]UsersPhoneNumber, error) {
	rows, err := q.db.Query(ctx, getUserPhoneNumbersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersPhoneNumber
	for rows.Next() {
		var i UsersPhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OwnerIsVerified,
			&i.Phone,
			&i.RawInput,
			&i.Phonecode,
			&i.OnWhatsapp,
			&i.IsDefault,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVerification = `-- name: GetUserVerification :one
SELECT user_id, nin_verified, phone_verified, email_verified, false AS voters_card_verified, email_verification_token, email_last_reminded_at, phone_last_reminded_at, created_at, updated_at FROM user_verifications
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserVerification(ctx context.Context, userID int64) (UserVerification, error) {
	row := q.db.QueryRow(ctx, getUserVerification, userID)
	var i UserVerification
	err := row.Scan(
		&i.UserID,
		&i.NinVerified,
		&i.PhoneVerified,
		&i.EmailVerified,
		&i.VotersCardVerified,
		&i.EmailVerificationToken,
		&i.EmailLastRemindedAt,
		&i.PhoneLastRemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.fake_id FROM users u
LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE 
  ($1::bigint IS NULL OR u.id < $1::bigint)
  AND ($2::text[] IS NULL OR EXISTS (
      SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role_code = ANY($2::text[])
  ))
  AND ($3::text IS NULL OR (
      COALESCE(up.first_name, '') ILIKE '%' || $3::text || '%' OR
      COALESCE(up.last_name, '') ILIKE '%' || $3::text || '%' OR
      COALESCE(u.username, '') ILIKE '%' || $3::text || '%'
  ))
  AND ($4::text[] IS NULL OR u.account_status = ANY($4::text[]))
  AND ($5::smallint[] IS NULL OR u.current_country = ANY($5::smallint[]))
  AND ($6::smallint[] IS NULL OR u.current_state = ANY($6::smallint[]))
ORDER BY u.id DESC
LIMIT $7::int
`

type ListUsersParams struct {
	Cursor              pgtype.Int8 `json:"cursor"`
	PartyID             pgtype.Int2 `json:"party_id"`
	PartyIds            []int16     `json:"party_ids"`
	VerificationTypeIds []int16     `json:"verification_type_ids"`
	RoleCodes           []string    `json:"role_codes"`
	Search              pgtype.Text `json:"search"`
	AccountStatus       []string    `json:"account_status"`
	CountryIds          []int16     `json:"country_ids"`
	StateIds            []int16     `json:"state_ids"`
	LimitNum            int32       `json:"limit_num"`
}

type ListUsersRow struct {
	ID       int64  `json:"id"`
	PublicID string `json:"public_id"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Cursor,
		arg.RoleCodes,
		arg.Search,
		arg.AccountStatus,
		arg.CountryIds,
		arg.StateIds,
		arg.LimitNum,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedUser = `-- name: SeedUser :one
INSERT INTO users (
  email, avatar, phone, username, password_hash, last_name, first_name, middle_name,
  gender, date_of_birth, current_country, current_state, current_lga, current_city,
  state_of_origin, voters_card_image,
  account_status, party_id, is_politician, is_verified
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id
`

type SeedUserParams struct {
	Email           pgtype.Text `json:"email"`
	Avatar          pgtype.Text `json:"avatar"`
	Phone           pgtype.Text `json:"phone"`
	Username        pgtype.Text `json:"username"`
	PasswordHash    string      `json:"password_hash"`
	LastName        pgtype.Text `json:"last_name"`
	FirstName       pgtype.Text `json:"first_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Gender          pgtype.Text `json:"gender"`
	DateOfBirth     pgtype.Date `json:"date_of_birth"`
	CurrentCountry  int16       `json:"current_country"`
	CurrentState    int16       `json:"current_state"`
	CurrentLga      pgtype.Int4 `json:"current_lga"`
	CurrentCity     pgtype.Int4 `json:"current_city"`
	StateOfOrigin   pgtype.Int2 `json:"state_of_origin"`
	VotersCardImage pgtype.Text `json:"voters_card_image"`
	AccountStatus   pgtype.Text `json:"account_status"`
	PartyID         pgtype.Int2 `json:"party_id"`
	IsPolitician    pgtype.Bool `json:"is_politician"`
	IsVerified      pgtype.Bool `json:"is_verified"`
}

func (q *Queries) SeedUser(ctx context.Context, arg SeedUserParams) (int64, error) {
	pubID := crypto.GeneratePublicID("usr")
	row := q.db.QueryRow(ctx, `
		INSERT INTO users (
			public_id, email, phone, username, password_hash, current_country, current_state, account_status
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id
	`,
		pubID,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.PasswordHash,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.AccountStatus,
	)
	var id int64
	err := row.Scan(&id)
	if err != nil {
		return 0, err
	}

	var dobVal *time.Time
	if arg.DateOfBirth.Valid {
		dobVal = &arg.DateOfBirth.Time
	}
	_, _ = q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, first_name, last_name, middle_name, gender, date_of_birth, profile_photo_url, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
		ON CONFLICT (user_id) DO NOTHING
	`, id, arg.FirstName.String, arg.LastName.String, arg.MiddleName.String, arg.Gender.String, dobVal, arg.Avatar.String)

	_, _ = q.db.Exec(ctx, `
		INSERT INTO user_verifications (user_id)
		VALUES ($1)
		ON CONFLICT (user_id) DO NOTHING
	`, id)

	return id, nil
}

type UpdateMoreInfoAboutThisUserParams struct {
	UserID            int64       `json:"user_id"`
	OccupationID      pgtype.Int2 `json:"occupation_id"`
	EducationalStatus pgtype.Text `json:"educational_status"`
	HighestDegree     pgtype.Text `json:"highest_degree"`
	GraduationYear    pgtype.Text `json:"graduation_year"`
	SchoolName        pgtype.Text `json:"school_name"`
	Religion          pgtype.Text `json:"religion"`
	MaritalStatus     pgtype.Text `json:"marital_status"`
	Address           pgtype.Text `json:"address"`
}

func (q *Queries) UpdateMoreInfoAboutThisUser(ctx context.Context, arg UpdateMoreInfoAboutThisUserParams) error {
	_, _ = q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, employment_status, updated_at)
		VALUES ($1, $2, NOW())
		ON CONFLICT (user_id) DO UPDATE
		SET employment_status = COALESCE(NULLIF(EXCLUDED.employment_status, ''), user_profiles.employment_status),
		    updated_at = NOW()
	`, arg.UserID, arg.EducationalStatus.String)

	if arg.Address.Valid && arg.Address.String != "" {
		_, _ = q.db.Exec(ctx, `
			INSERT INTO addresses (user_id, address_type, line_1, city, country_code, is_current, updated_at)
			VALUES ($1, 'residential', $2, 'Unknown', 'NG', true, NOW())
			ON CONFLICT DO NOTHING
		`, arg.UserID, arg.Address.String)
	}
	return nil
}

type UpdateOnboardingProfileParams struct {
	ID              int64       `json:"id"`
	Username        pgtype.Text `json:"username"`
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Gender          pgtype.Text `json:"gender"`
	DateOfBirth     pgtype.Date `json:"date_of_birth"`
	CurrentCountry  int16       `json:"current_country"`
	CurrentState    int16       `json:"current_state"`
	CurrentCity     pgtype.Int4 `json:"current_city"`
	StateOfOrigin   pgtype.Int2 `json:"state_of_origin"`
	CountryOfOrigin pgtype.Int2 `json:"country_of_origin"`
	ReferralCode    pgtype.Text `json:"referral_code"`
}

func (q *Queries) UpdateOnboardingProfile(ctx context.Context, arg UpdateOnboardingProfileParams) (User, error) {
	_, err := q.db.Exec(ctx, `
		UPDATE users
		SET username = COALESCE(NULLIF($2, ''), username),
		    current_country = COALESCE(NULLIF($3, 0), current_country),
		    current_state = COALESCE(NULLIF($4, 0), current_state),
		    referral_code = COALESCE(NULLIF($5, ''), referral_code),
		    account_status = 'active',
		    updated_at = NOW()
		WHERE id = $1
	`, arg.ID, arg.Username.String, arg.CurrentCountry, arg.CurrentState, arg.ReferralCode.String)
	if err != nil {
		return User{}, err
	}

	var dobVal *time.Time
	if arg.DateOfBirth.Valid {
		dobVal = &arg.DateOfBirth.Time
	}
	_, err = q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, first_name, last_name, middle_name, gender, date_of_birth, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, NOW())
		ON CONFLICT (user_id) DO UPDATE
		SET first_name = COALESCE(NULLIF(EXCLUDED.first_name, ''), user_profiles.first_name),
		    last_name = COALESCE(NULLIF(EXCLUDED.last_name, ''), user_profiles.last_name),
		    middle_name = COALESCE(NULLIF(EXCLUDED.middle_name, ''), user_profiles.middle_name),
		    gender = COALESCE(NULLIF(EXCLUDED.gender, ''), user_profiles.gender),
		    date_of_birth = COALESCE(EXCLUDED.date_of_birth, user_profiles.date_of_birth),
		    updated_at = NOW()
	`, arg.ID, arg.FirstName.String, arg.LastName.String, arg.MiddleName.String, arg.Gender.String, dobVal)
	if err != nil {
		return User{}, err
	}

	if arg.CurrentCity.Valid && arg.CurrentCity.Int32 > 0 {
		_, _ = q.db.Exec(ctx, `
			INSERT INTO addresses (user_id, address_type, line_1, city, country_code, is_current, updated_at)
			VALUES ($1, 'residential', 'Pending verification', $2, 'NG', true, NOW())
			ON CONFLICT DO NOTHING
		`, arg.ID, fmt.Sprintf("%d", arg.CurrentCity.Int32))
	}

	return User{
		ID:             arg.ID,
		Username:       arg.Username,
		FirstName:      arg.FirstName,
		LastName:       arg.LastName,
		MiddleName:     arg.MiddleName,
		Gender:         arg.Gender,
		DateOfBirth:    arg.DateOfBirth,
		CurrentCountry: arg.CurrentCountry,
		CurrentState:   arg.CurrentState,
		ReferralCode:   arg.ReferralCode,
		AccountStatus:  pgtype.Text{String: "active", Valid: true},
	}, nil
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
UPDATE users_phone_numbers
SET on_whatsapp = $3,
    is_default = $4
WHERE id = $1 AND user_id = $2
`

type UpdatePhoneNumberParams struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	OnWhatsapp pgtype.Bool `json:"on_whatsapp"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updatePhoneNumber,
		arg.ID,
		arg.UserID,
		arg.OnWhatsapp,
		arg.IsDefault,
	)
	return err
}

type UpdateUserAgentMoreInfoParams struct {
	UserID            int64       `json:"user_id"`
	EducationalStatus pgtype.Text `json:"educational_status"`
	HighestDegree     pgtype.Text `json:"highest_degree"`
	GraduationYear    pgtype.Text `json:"graduation_year"`
	SchoolName        pgtype.Text `json:"school_name"`
	Address           pgtype.Text `json:"address"`
}

func (q *Queries) UpdateUserAgentMoreInfo(ctx context.Context, arg UpdateUserAgentMoreInfoParams) error {
	if arg.Address.Valid && arg.Address.String != "" {
		_, _ = q.db.Exec(ctx, `
			INSERT INTO addresses (user_id, address_type, line_1, city, country_code, is_current, updated_at)
			VALUES ($1, 'residential', $2, 'Unknown', 'NG', true, NOW())
			ON CONFLICT DO NOTHING
		`, arg.UserID, arg.Address.String)
	}
	return nil
}

type UpdateUserAvatarParams struct {
	ID           int64       `json:"id"`
	Avatar       pgtype.Text `json:"avatar"`
	AvatarFileID pgtype.Int8 `json:"avatar_file_id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, profile_photo_url, updated_at)
		VALUES ($1, $2, NOW())
		ON CONFLICT (user_id) DO UPDATE
		SET profile_photo_url = EXCLUDED.profile_photo_url,
		    updated_at = NOW()
	`, arg.ID, arg.Avatar.String)
	return err
}

type UpdateUserDegreeCertificateUrlParams struct {
	UserID               int64       `json:"user_id"`
	DegreeCertificateUrl pgtype.Text `json:"degree_certificate_url"`
}

func (q *Queries) UpdateUserDegreeCertificateUrl(ctx context.Context, arg UpdateUserDegreeCertificateUrlParams) error {
	return nil
}

const updateUserPublicID = `-- name: UpdateUserPublicID :exec
UPDATE users
SET public_id = $2
WHERE id = $1
`

type UpdateUserPublicIDParams struct {
	ID       int64  `json:"id"`
	PublicID string `json:"public_id"`
}

type UpdateUserFakeIDParams = UpdateUserPublicIDParams

func (q *Queries) UpdateUserPublicID(ctx context.Context, arg UpdateUserPublicIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPublicID, arg.ID, arg.PublicID)
	return err
}

func (q *Queries) UpdateUserFakeID(ctx context.Context, arg UpdateUserPublicIDParams) error {
	return q.UpdateUserPublicID(ctx, arg)
}

type UpdateUserHasRoleParams struct {
	ID      int64       `json:"id"`
	HasRole pgtype.Bool `json:"has_role"`
}

func (q *Queries) UpdateUserHasRole(ctx context.Context, arg UpdateUserHasRoleParams) error {
	return nil
}

const updateUserPasswordByPublicID = `-- name: UpdateUserPasswordByPublicID :exec
UPDATE users
SET password_hash = $2
WHERE public_id = $1
`

type UpdateUserPasswordByPublicIDParams struct {
	PublicID     string `json:"public_id"`
	PasswordHash string `json:"password_hash"`
}

type UpdateUserPasswordByFidParams = UpdateUserPasswordByPublicIDParams

func (q *Queries) UpdateUserPasswordByPublicID(ctx context.Context, arg UpdateUserPasswordByPublicIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByPublicID, arg.PublicID, arg.PasswordHash)
	return err
}

func (q *Queries) UpdateUserPasswordByFid(ctx context.Context, arg UpdateUserPasswordByPublicIDParams) error {
	return q.UpdateUserPasswordByPublicID(ctx, arg)
}

type UpdateUserProfileParams struct {
	ID             int64       `json:"id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Gender         pgtype.Text `json:"gender"`
	Avatar         pgtype.Text `json:"avatar"`
	AvatarFileID   pgtype.Int8 `json:"avatar_file_id"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, `
		UPDATE users
		SET current_country = COALESCE(NULLIF($2, 0), current_country),
		    current_state = COALESCE(NULLIF($3, 0), current_state),
		    updated_at = NOW()
		WHERE id = $1
	`, arg.ID, arg.CurrentCountry, arg.CurrentState)
	if err != nil {
		return err
	}

	_, err = q.db.Exec(ctx, `
		INSERT INTO user_profiles (user_id, first_name, last_name, middle_name, gender, profile_photo_url, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, NOW())
		ON CONFLICT (user_id) DO UPDATE
		SET first_name = COALESCE(NULLIF(EXCLUDED.first_name, ''), user_profiles.first_name),
		    last_name = COALESCE(NULLIF(EXCLUDED.last_name, ''), user_profiles.last_name),
		    middle_name = COALESCE(NULLIF(EXCLUDED.middle_name, ''), user_profiles.middle_name),
		    gender = COALESCE(NULLIF(EXCLUDED.gender, ''), user_profiles.gender),
		    profile_photo_url = COALESCE(NULLIF(EXCLUDED.profile_photo_url, ''), user_profiles.profile_photo_url),
		    updated_at = NOW()
	`, arg.ID, arg.FirstName.String, arg.LastName.String, arg.MiddleName.String, arg.Gender.String, arg.Avatar.String)
	return err
}

const updateUserReferralCode = `-- name: UpdateUserReferralCode :exec
UPDATE users
SET referral_code = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserReferralCodeParams struct {
	ID           int64       `json:"id"`
	ReferralCode pgtype.Text `json:"referral_code"`
}

func (q *Queries) UpdateUserReferralCode(ctx context.Context, arg UpdateUserReferralCodeParams) error {
	_, err := q.db.Exec(ctx, updateUserReferralCode, arg.ID, arg.ReferralCode)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET account_status = $2
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID            int64       `json:"id"`
	AccountStatus pgtype.Text `json:"account_status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.AccountStatus)
	return err
}

const updateUserVotersCard = `-- name: UpdateUserVotersCard :exec
UPDATE users
SET voters_card_image = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserVotersCardParams struct {
	ID              int64       `json:"id"`
	VotersCardImage pgtype.Text `json:"voters_card_image"`
}

func (q *Queries) UpdateUserVotersCard(ctx context.Context, arg UpdateUserVotersCardParams) error {
	_, err := q.db.Exec(ctx, updateUserVotersCard, arg.ID, arg.VotersCardImage)
	return err
}

const upsertUserPhoneNumber = `-- name: UpsertUserPhoneNumber :one
INSERT INTO users_phone_numbers (user_id, phone, phonecode, raw_input, on_whatsapp, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (phone) DO UPDATE
SET on_whatsapp = EXCLUDED.on_whatsapp,
    is_active = true
RETURNING id
`

type UpsertUserPhoneNumberParams struct {
	UserID     int64       `json:"user_id"`
	Phone      string      `json:"phone"`
	Phonecode  string      `json:"phonecode"`
	RawInput   string      `json:"raw_input"`
	OnWhatsapp pgtype.Bool `json:"on_whatsapp"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpsertUserPhoneNumber(ctx context.Context, arg UpsertUserPhoneNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserPhoneNumber,
		arg.UserID,
		arg.Phone,
		arg.Phonecode,
		arg.RawInput,
		arg.OnWhatsapp,
		arg.IsDefault,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
